# Generated by Django 2.2.3 on 2019-07-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190710_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='categoria',
            field=models.CharField(max_length=30),
        ),
    ]
