# Generated by Django 2.2.3 on 2019-07-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190710_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='categoria',
            field=models.IntegerField(),
        ),
    ]
