# Generated by Django 2.2.3 on 2019-07-10 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20190710_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='user',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
